# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enterprise.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOfServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name category of cervices', max_length=255)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Priority')),
            ],
            options={
                'verbose_name': 'Category of service',
                'verbose_name_plural': 'Category of services',
                'db_table': 'Category_of_services',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name enterprise', max_length=255)),
                ('logo', models.ImageField(help_text='Logo image', upload_to=enterprise.models.upload_enterprise_image)),
                ('short_descr', models.TextField(help_text='Short descriptions')),
                ('schedule', models.TextField(help_text='Schedule enterprise')),
                ('address', models.CharField(help_text='Address enterprise', max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone', max_length=255)),
                ('coordinate_lat', models.FloatField(help_text='Latitude')),
                ('coordinate_lon', models.FloatField(help_text='Longitude')),
                ('active_stuff_count', models.PositiveIntegerField(default=0, help_text='Active stuff')),
                ('group_priority', models.PositiveIntegerField(help_text='Enterprise priority from filter')),
                ('city', models.ForeignKey(help_text='Select city', on_delete=django.db.models.deletion.CASCADE, to='enterprise.City')),
                ('owner', models.ForeignKey(help_text='Owner field', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enterprise',
                'db_table': 'Enterprise',
                'ordering': ['-group_priority'],
            },
        ),
        migrations.AddField(
            model_name='categoryofservices',
            name='enterprise',
            field=models.ForeignKey(help_text='Select enterprise', on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise'),
        ),
    ]
