# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], help_text='Gender', max_length=50, verbose_name='Gender')),
                ('birth', models.DateField(blank=True, help_text='You date of birth', null=True)),
                ('address', models.CharField(help_text='Contact address: City, Str, apt', max_length=255, verbose_name='Address')),
                ('contact_email', models.EmailField(blank=True, help_text='example@provider.com', max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Phone')),
                ('about', models.TextField(blank=True, help_text='Say something about yourself')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'ClientProfile',
            },
        ),
        migrations.AlterUniqueTogether(
            name='clientprofile',
            unique_together=set([('user', 'address', 'contact_email')]),
        ),
    ]
