# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of employees', max_length=255)),
                ('specialization', models.CharField(help_text='Specialization', max_length=255)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Weight for sorted')),
                ('show_rating', models.BooleanField(default=False, help_text='Show rating employees')),
                ('rating', models.PositiveIntegerField(default=0, help_text='Rating')),
                ('votes_count', models.PositiveIntegerField(default=0, help_text='Votes count')),
                ('avatar', models.ImageField(blank=True, help_text='Avatar', upload_to=employee.models.upload_employee_avatar_image)),
                ('information', models.TextField(help_text='More info')),
                ('hidden', models.BooleanField(default=False, help_text='Hidden for booking')),
                ('fired', models.BooleanField(default=False, help_text='Is fired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise')),
                ('service', models.ForeignKey(help_text='Select category of services', on_delete=django.db.models.deletion.CASCADE, to='enterprise.CategoryOfServices')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'Employee',
                'ordering': ['-weight'],
            },
        ),
    ]
