# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('client_name', models.CharField(help_text='First and Last name', max_length=255)),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone in format (+*********)', max_length=128)),
                ('description', models.TextField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.Enterprise')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'verbose_name': 'Online Booking',
                'verbose_name_plural': 'Online Booking',
                'db_table': 'online_booking',
                'ordering': ['-date'],
            },
        ),
    ]
